include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'
    - 'lib/gen/**'
    - '**/nooki_icons.dart'
    - '**/firebase_options.dart'

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false
    avoid_positional_boolean_parameters: false
    prefer_relative_imports: true
    always_use_package_imports: false
    unawaited_futures: false

