name: cashfy
description: "Money app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  retrofit: ^4.0.3
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.1
  flutter_gen: ^5.3.1
  auto_route: ^7.7.1
  flutter_native_splash: ^2.3.10
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  flutter_form_builder: ^9.1.0
  flutter_hooks: ^0.20.0
  flutter_secure_storage: ^9.0.0
  rxdart: ^0.27.7
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  very_good_analysis: ^5.1.0
  hooks_riverpod: ^2.4.3
  cached_network_image: ^3.3.0
  flutter_launcher_icons: ^0.13.1
  fpdart: ^1.1.0
  logger: ^2.0.2+1
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.2.1
  url_launcher: ^6.2.1
  equatable: ^2.0.5
  smooth_page_indicator: ^1.1.0
  expandable_page_view: ^1.0.17
  shared_preferences: ^2.2.2
  modal_bottom_sheet: ^3.0.0-pre
  dropdown_button2: ^2.3.9
  mask_text_input_formatter: ^2.5.0
  shimmer: ^3.0.0
  flutter_image_compress: ^2.1.0
  popover: ^0.2.9
  path: ^1.8.3
  package_info_plus: ^5.0.1
  flutter_rating_bar: ^4.0.1
  bottom_sheet: ^4.0.0
  path_provider: ^2.1.2
  clipboard: ^0.1.3
  share_plus: ^7.2.2
  riverpod: ^2.5.0
  supabase_flutter: ^2.3.3
  flutter_dotenv: ^5.1.0
  analyzer: ^6.2.0
  webview_flutter: ^4.7.0
  another_flushbar: ^1.12.30
  flutter_keyboard_visibility: ^6.0.0
  pin_code_fields: ^8.0.1
  animated_expandable_fab: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  auto_route_generator: ^7.1.2
  riverpod_generator: ^2.3.5
  retrofit_generator: ^8.0.5

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#7F3DFF"
  image: "assets/images/logo.png"


  android_12:
    color: "#7F3DFF"
    image: "assets/images/logo.png"
#    branding: "assets/images/branding.png"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  background_color: "#7F3DFF"
  adaptive_icon_background: "#7F3DFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/svg/

flutter_intl:
  enabled: true
  class_name: S
  arb_dir: assets/l10n
  output_dir: lib/gen
  synthetic_package: false